# Generated by Django 5.1.6 on 2025-03-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatik', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
