# Generated by Django 5.1.6 on 2025-03-03 17:17

import Chatik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatik', '0005_chatroom_message_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='password',
            field=models.CharField(max_length=120, validators=[Chatik.models.chat_room_password]),
        ),
    ]
